import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import { useEffect, useState } from "react";
import LoadingBar from "react-top-loading-bar";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import ProductList from "../components/ProductList";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  // const [progress, setProgress] = useState(0)
  // const router = useRouter();

  // useEffect(() => {
  //   router.events.on('routeChangeComplete',()=>{
  //     setProgress(100)
  //   })
  // }, [router])
  

  return (
    // <div className={styles.container}>
    <div>
      <Head>
        <title>Anna Purna.</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/faviconmain.ico" />
        {/* <link rel="stylesheet" href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css" /> */}
      </Head>
      {/* <Script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"/> */}
    {/* <LoadingBar
        color='#f11946'
        progress={progress}
        onLoaderFinished={() => setProgress(0)}
      /> */}
      <Navbar/>
      <Header/>
      <br/>
      <ProductList/>
      <Footer/>
      </div>
    // </div>
  );
}
